# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpc_generated_files.RoutesAnalysis_pb2 as RoutesAnalysis__pb2


class RoutesAnalysisStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Analyse = channel.unary_unary(
                '/routes_analysis.RoutesAnalysis/Analyse',
                request_serializer=RoutesAnalysis__pb2.AnalyseRequest.SerializeToString,
                response_deserializer=RoutesAnalysis__pb2.AnalyseResponse.FromString,
                )


class RoutesAnalysisServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Analyse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoutesAnalysisServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Analyse': grpc.unary_unary_rpc_method_handler(
                    servicer.Analyse,
                    request_deserializer=RoutesAnalysis__pb2.AnalyseRequest.FromString,
                    response_serializer=RoutesAnalysis__pb2.AnalyseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'routes_analysis.RoutesAnalysis', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RoutesAnalysis(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Analyse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/routes_analysis.RoutesAnalysis/Analyse',
            RoutesAnalysis__pb2.AnalyseRequest.SerializeToString,
            RoutesAnalysis__pb2.AnalyseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
