// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db_queries

import (
	"encoding/json"
	"time"
)

type RoutesHistory struct {
	ID        int64
	CreatedAt time.Time
	Data      json.RawMessage
	RefUserID int32
}

type User struct {
	ID       int64
	Login    string
	Password string
}
