// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db_queries

import (
	"time"

	"backend-hagowagonetka/internal/repository/dto"
)

type RoutesHistory struct {
	ID        int64
	CreatedAt time.Time
	Data      *dto.RoutesHistoryData
	RefUserID int32
}

type User struct {
	ID       int64
	Login    string
	Password string
}
