// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db_queries

import (
	"time"
)

type Station struct {
	ID        int64
	CreatedAt time.Time
	Name      string
	Geoname   string
	Lon       float64
	Lat       float64
	RefUserID int64
}

type User struct {
	ID       int64
	Login    string
	Password string
}
