// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: query.sql

package db_queries

import (
	"context"
	"database/sql"
)

const pointCreate = `-- name: PointCreate :one
INSERT INTO points (
    lat, lon
) VALUES (
    $1, $2
) 
RETURNING id, lat, lon
`

type PointCreateParams struct {
	Lat sql.NullString
	Lon sql.NullString
}

func (q *Queries) PointCreate(ctx context.Context, arg PointCreateParams) (Point, error) {
	row := q.db.QueryRowContext(ctx, pointCreate, arg.Lat, arg.Lon)
	var i Point
	err := row.Scan(&i.ID, &i.Lat, &i.Lon)
	return i, err
}
