// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: proto/RoutesAnalysis.proto

package pb_routes_analysis

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Distance    int64 `protobuf:"varint,1,opt,name=distance,proto3" json:"distance,omitempty"`                          // расстояния в километрах между точками
	Timestamp   int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                        // время отправления
	CargoTotal  int32 `protobuf:"varint,3,opt,name=cargo_total,json=cargoTotal,proto3" json:"cargo_total,omitempty"`    // общее кол-во грузов
	CargoFilled int32 `protobuf:"varint,4,opt,name=cargo_filled,json=cargoFilled,proto3" json:"cargo_filled,omitempty"` // заполненное кол-во грузов
}

func (x *AnalyseRequest) Reset() {
	*x = AnalyseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RoutesAnalysis_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnalyseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyseRequest) ProtoMessage() {}

func (x *AnalyseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RoutesAnalysis_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyseRequest.ProtoReflect.Descriptor instead.
func (*AnalyseRequest) Descriptor() ([]byte, []int) {
	return file_proto_RoutesAnalysis_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyseRequest) GetDistance() int64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *AnalyseRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AnalyseRequest) GetCargoTotal() int32 {
	if x != nil {
		return x.CargoTotal
	}
	return 0
}

func (x *AnalyseRequest) GetCargoFilled() int32 {
	if x != nil {
		return x.CargoFilled
	}
	return 0
}

type AnalyseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeSpent float32 `protobuf:"fixed32,1,opt,name=time_spent,json=timeSpent,proto3" json:"time_spent,omitempty"` // затраченное время в минутах
}

func (x *AnalyseResponse) Reset() {
	*x = AnalyseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RoutesAnalysis_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnalyseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyseResponse) ProtoMessage() {}

func (x *AnalyseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RoutesAnalysis_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyseResponse.ProtoReflect.Descriptor instead.
func (*AnalyseResponse) Descriptor() ([]byte, []int) {
	return file_proto_RoutesAnalysis_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyseResponse) GetTimeSpent() float32 {
	if x != nil {
		return x.TimeSpent
	}
	return 0
}

var File_proto_RoutesAnalysis_proto protoreflect.FileDescriptor

var file_proto_RoutesAnalysis_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x41, 0x6e,
	0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x72, 0x6f,
	0x75, 0x74, 0x65, 0x73, 0x5f, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x22, 0x8e, 0x01,
	0x0a, 0x0e, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61,
	0x72, 0x67, 0x6f, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x63,
	0x61, 0x72, 0x67, 0x6f, 0x5f, 0x66, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x46, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x22, 0x30,
	0x0a, 0x0f, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x70, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x70, 0x65, 0x6e, 0x74,
	0x32, 0x5e, 0x0a, 0x0e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73,
	0x69, 0x73, 0x12, 0x4c, 0x0a, 0x07, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x65, 0x12, 0x1f, 0x2e,
	0x72, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x5f, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2e,
	0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20,
	0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x5f, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73,
	0x2e, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x21, 0x5a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67,
	0x2f, 0x70, 0x62, 0x2d, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x2d, 0x61, 0x6e, 0x61, 0x6c, 0x79,
	0x73, 0x69, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_RoutesAnalysis_proto_rawDescOnce sync.Once
	file_proto_RoutesAnalysis_proto_rawDescData = file_proto_RoutesAnalysis_proto_rawDesc
)

func file_proto_RoutesAnalysis_proto_rawDescGZIP() []byte {
	file_proto_RoutesAnalysis_proto_rawDescOnce.Do(func() {
		file_proto_RoutesAnalysis_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_RoutesAnalysis_proto_rawDescData)
	})
	return file_proto_RoutesAnalysis_proto_rawDescData
}

var file_proto_RoutesAnalysis_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_RoutesAnalysis_proto_goTypes = []interface{}{
	(*AnalyseRequest)(nil),  // 0: routes_analysis.AnalyseRequest
	(*AnalyseResponse)(nil), // 1: routes_analysis.AnalyseResponse
}
var file_proto_RoutesAnalysis_proto_depIdxs = []int32{
	0, // 0: routes_analysis.RoutesAnalysis.Analyse:input_type -> routes_analysis.AnalyseRequest
	1, // 1: routes_analysis.RoutesAnalysis.Analyse:output_type -> routes_analysis.AnalyseResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_RoutesAnalysis_proto_init() }
func file_proto_RoutesAnalysis_proto_init() {
	if File_proto_RoutesAnalysis_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_RoutesAnalysis_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnalyseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_RoutesAnalysis_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnalyseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_RoutesAnalysis_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_RoutesAnalysis_proto_goTypes,
		DependencyIndexes: file_proto_RoutesAnalysis_proto_depIdxs,
		MessageInfos:      file_proto_RoutesAnalysis_proto_msgTypes,
	}.Build()
	File_proto_RoutesAnalysis_proto = out.File
	file_proto_RoutesAnalysis_proto_rawDesc = nil
	file_proto_RoutesAnalysis_proto_goTypes = nil
	file_proto_RoutesAnalysis_proto_depIdxs = nil
}
